### PR TITLE
Update index.js to support webpack 2

### PR DESCRIPTION
**Pull request by RahavLussato**

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Oh! I had totally overseen that your issue actually pointed at a pull request. o.o! I'll review the commits.

**Comment by IngwiePhoenix** [comment]
I actually learned something from this PR. Thanks! Merging.

**Comment by IngwiePhoenix** [comment]
Done. `2.0.3` has this commit in.

**Comment by RahavLussato** [comment]
:+1

**Pull request merged**
